### ISSUE TITLE
Download the UI Kit or use cdn already there in starter project?

### ISSUE THREAD

**Issue by timurista** [zero-to-mastery/Coding_Challenge-8#1]
Hey Andrei, looking at code challenge 8 you recently posted. The rule states to use NOW UI Kit: https://www.creative-tim.com/product/now-ui-kit. however the index.html from starter project looks like it already has the now cdn "https://cdn.rawgit.com/creativetimofficial/now-ui-kit/. Do we just have to make sure to use now via that cdn already in the index.html (basically don't delete it) or do we need to download some css file from the product/now-ui-kit website and add it to our list of project files?

**Comment by aneagoie** [comment]
Nope, it's included already so you can just use the UI kit as it is

**Comment by timurista** [comment]
Thanks!
